### ISSUE TITLE
Manual syntax rebuild

### ISSUE THREAD

**Issue by tophmatthews** [dschwen/autocomplete-moose#10]
(I keep bugging you I know, but they're just quirks I've noticed, no show stoppers for this great tool!)

There seems to be a preference for dbg builds over opt. I usually work in opt (maybe that is bad work flow) so if there is a dbg lying around, the moose syntax will work off that. If I delete dbg, it'll still use the old syntax. It'd be nice to have a way to manually rebuild the syntax. The work around now is to restart atom.

**Comment by dschwen** [comment]
You can reload the current editor with ctrl-cmd-alt-L
But, yeah, the preference should be given to the newest executable.

**Comment by dschwen** [comment]
Now that I think about it have you tried the "Autocomplete Moose: Clear Cache" command from the Command palette (Shift-Cmd-P)?

**Comment by dschwen** [comment]
Also, it should already utilize the most recent executable. I don't understand why it seems to prefer dbg in your case.

https://github.com/dschwen/autocomplete-moose/blob/master/lib/provider.coffee#L593

Are you using symlinks to your apps. In that case maybe it is using the symlink creation date for sorting :-/

**Comment by tophmatthews** [comment]
Oh there is option already! nice!

**Comment by tophmatthews** [comment]
This in the app folder directly, no symlinks.
