### ISSUE TITLE
autocomplete for AD kernels and materials

### ISSUE THREAD

**Issue by tophmatthews** [dschwen/autocomplete-moose#13]
Keeps wanting to autocomplete to `ADSomeKernel<Residual>`. When `type = ADSomeKernel`, autocomplete won't find the rest of the object input parameters.

**Comment by dschwen** [comment]
That's weird

**Comment by tophmatthews** [comment]
I still get the same behavior, am I missing something?

**Comment by dschwen** [comment]
No. I figured out what the issue is (MOOSE outputs the objects names including the <RESIDUAL> or <JACOBIAN> template parameters, but expects them without those in the input files). We either need to make the dump sane or strip the template crap off in the autocomplete plugin.

**Comment by tophmatthews** [comment]
Seems like the dump should also show what the input file expects

**Comment by tophmatthews** [comment]
Fixed via moose dump
