### ISSUE TITLE
Autocomplete box sometimes does not/cannot show after partial completion

### ISSUE THREAD

**Issue by joshuahansel** [dschwen/autocomplete-moose#18]
When on a blank line in my input file, I can always bring up the autocomplete box with the keyboard shortcut. However, for some blocks/sub-blocks, after I type part of a parameter name, the box disappears (even though there is a match), and I cannot even bring it back with the keyboard shortcut.

For example, the following input file in the MOOSE repo:
```
moose/test/tests/kernels/simple_diffusion/simple_diffusion.i
```
This happens in `Kernels/diff` but not in `BCs/left`.

I'm using Atom 1.47.0, autocomplete-moose 1.0.0.

**Comment by joshuahansel** [comment]
@dschwen The problem occurs with both "old" or "new" block syntax, but I think this worked correctly before recent changes.

**Comment by dschwen** [comment]
Can you try the master branch, with my current development version I cannot replicate this behavior.

**Comment by joshuahansel** [comment]
The master branch works.
