### ISSUE TITLE
Allow autocomplete for compressed actions

### ISSUE THREAD

**Issue by tophmatthews** [dschwen/autocomplete-moose#6]
Autocomplete doesn't recognize compressed action headers. For example:

```
[Modules/TensorMechanics/Master]
  [./pellets]
    blah blah blah...
  [../]
[]
```
isn't recognized, but

```
[Modules]
  [./TensorMechanics]
    [./Master]
      [./all]
        blah blah blah...
      [../]
    [../]
  [../]
[]
```
is able to use autocomplete

**Comment by dschwen** [comment]
Oh, I already have a version that allows input block paths with multiple slashes on my machine...

I guess I should make a release

**Comment by dschwen** [comment]
Done. What this is still missing is completing the action path with the multiple slashes. I'll work on that next.

**Comment by tophmatthews** [comment]
quick, thanks!

**Comment by dschwen** [comment]
Uh oh, have you given up on me?

**Comment by tophmatthews** [comment]
No I think it got fixed along the way?

**Comment by tophmatthews** [comment]
There’s the others that are still open however....slacker.... :)
