### ISSUE TITLE
Add hidden file with path to fallback executible

### ISSUE THREAD

**Issue by tophmatthews** [dschwen/autocomplete-moose#8]
The `Fallback Moose Dir` option is great, especially when there are tools (i.e. collection of scripts, inputs, etc) adjacent to the necessary app. However, once set, it is the same across all projects. It'd be great to have an optional hidden settings file, something like ".autocomplete_fallback_dir" that can be included in the tools repo which automatically sets the `Fallback Moose Dir`. That way it can be project specific.

Ex:
```
~/projects/marmot/  <- code repo directory
~/projects/marmot_tools/ <- tools, scripts, input repo directory
~/projects/marmot_tools/.autocomplete_fallback_dir <- reads '~/projects/marmot/'

~/projects/bison/  <- code repo directory
~/projects/bison_tools/ <- tools, scripts, input repo directory
~/projects/bison_tools/.autocomplete_fallback_dir <- reads '~/projects/bison/'
```

**Comment by dschwen** [comment]
As a workaround in the meantime you can put a symbolic link to any MOOSE executable in your tools directory.

**Comment by tophmatthews** [comment]
Oh nice, good idea
